### ISSUE TITLE
Given that I'm a registered user, when I go to the login page, enter my username and an incorrect password and click on Log in; log in should fail and display error message specifying that username or password was wrong

### ISSUE THREAD

**Issue by annagabriel-hash** [annagabriel-hash/journal-app#10]
### Tasks

- [x] Specify user login with invalid inputs
- [x] Validates username and password
- [x] Generates error message for invalid inputs
