### ISSUE TITLE
When visitors go to the homepage and click the signup link, users are redirected to the sign up form where they can input their username, first name, last name and password to create their new account.

### ISSUE THREAD

**Issue by annagabriel-hash** [annagabriel-hash/journal-app#29]
## Task
- [x] Specify redirect to signup page
- [x] Add client side form validation
- [x] Update signup link
- [x] Update signup form styling
