### ISSUE TITLE
US #8: As a User, I want to view my tasks for today for me to remind what are my priorities for today

### ISSUE THREAD

**Issue by annagabriel-hash** [annagabriel-hash/journal-app#3]
### User Story (U.S.) #10
**Description**
As a User, I want to view my tasks for today for me to remind what are my priorities for today

**Tasks**
- [ ] Add user to task association
- [ ] Add due date for the task
- [ ] Update user controller to retrieve the tasks for the day
- [ ] Add views/templates to display tasks for the day
