### ISSUE TITLE
Create login feature

### ISSUE THREAD

**Issue by annagabriel-hash** [annagabriel-hash/journal-app#8]
### Tasks

- [x] Added login route
- [x] Added sessions controller
- [x] Added login page and form
- [x] Added success message upon logging in
